Repository enter-at/node-aws-lambda-handlers, pull requests merged in 2020-07, with the labels that each got.

#207 Request timeout error
  package-lock.json
  src/error/RequestTimeoutError.ts
  src/error/index.ts
  src/handler/APIGatewayProxyHandler.spec.ts
  src/handler/APIGatewayProxyHandler.ts
  src/handler/__snapshots__/APIGatewayProxyHandler.spec.ts.snap
  src/response.ts
  test/fixtures/APIGatewayProxyEventFactory.ts
  test/fixtures/ContextFactory.ts
Labels: size/L

#215 Tests for successful HTTP responses
  README.md
  README.yaml
  package.json
  src/handler/APIGatewayProxyHandler.spec.ts
  src/handler/__snapshots__/APIGatewayProxyHandler.spec.ts.snap
Labels: size/M

#218 Expose and handle UnauthorizedError
  .eslintignore
  .eslintrc.js
  .github/workflows/lint-and-test.yml
  package-lock.json
  package.json
  src/decorator/format/index.ts
  src/decorator/handler/index.ts
  src/decorator/header/index.ts
  src/error/BadRequestError.ts
  src/error/ForbiddenError.ts
  src/error/FormatError.ts
  src/error/InternalServerError.ts
  src/error/LambdaHandlerError.ts
  src/error/NotFoundError.ts
  src/error/RequestTimeoutError.ts
  src/error/UnauthorizedError.ts
  src/error/ValidationError.ts
  src/error/index.ts
  src/format/Format.ts
  src/format/IFormat.ts
  src/format/InputFormat.spec.ts
  src/format/InputFormat.ts
  src/format/OutputFormat.ts
  src/handler/APIGatewayProxyHandler.spec.ts
  src/handler/APIGatewayProxyHandler.ts
  src/handler/BaseHandler.ts
  src/handler/__snapshots__/APIGatewayProxyHandler.spec.ts.snap
  src/handler/index.ts
  src/header/CORSHeader.ts
  src/header/ContentTypeHeader.ts
  src/header/Header.ts
  src/header/IHeader.ts
  src/header/index.ts
  src/index.ts
  src/response.ts
  tsconfig.build.json
  tsconfig.json
  tslint.json
Labels: size/XL
